spring:
  application:
    name: server-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/morge007/SpringcloudConfig.git
          search-paths: respo
#          username: username
#          password: password
      label: master
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8889/eureka/
